version: '3.8'

services:
  # Backend API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: barbot-server
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/__pycache__
    networks:
      - barbot-network

  # Frontend web service
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: barbot-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - barbot-network

networks:
  barbot-network:
    driver: bridge
